sonar.projectKey=ibrahim123-sia_ibrahim-ali-mern-10pshine
sonar.organization=ibrahim123-sia

sonar.sources=backend,frontend/src
sonar.tests=backend/tests

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/uploads/**,frontend/public/**
sonar.test.inclusions=backend/tests/**/*.test.js
sonar.coverage.exclusions=backend/server.js,backend/configs/db.js,backend/configs/logger.js,backend/routes/**,frontend/src/**

sonar.issue.ignore.multicriteria=e1,e2,e3,e4
sonar.issue.ignore.multicriteria.e1.ruleKey=javascript:S6774
sonar.issue.ignore.multicriteria.e1.resourceKey=frontend/src/**/*
sonar.issue.ignore.multicriteria.e2.ruleKey=javascript:S3776
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*
sonar.issue.ignore.multicriteria.e3.ruleKey=javascript:S1192
sonar.issue.ignore.multicriteria.e3.resourceKey=**/*
sonar.issue.ignore.multicriteria.e4.ruleKey=javascript:S6853
sonar.issue.ignore.multicriteria.e4.resourceKey=frontend/src/**/*

sonar.sourceEncoding=UTF-8
