sonar.projectKey=ibrahim123-sia_ibrahim-ali-mern-10pshine
sonar.organization=ibrahim123-sia

sonar.sources=backend,frontend/src
sonar.tests=backend/tests

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/uploads/**,frontend/public/**
sonar.test.inclusions=backend/tests/**/*.test.js
sonar.coverage.exclusions=backend/server.js,backend/configs/db.js,backend/configs/logger.js,backend/routes/**,frontend/src/**

sonar.sourceEncoding=UTF-8
